version: "3"
services:
    app:
        build:
            args:
                user: nginx
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: umkm
        container_name: umkm-app
        restart: unless-stopped
        working_dir: /var/www/html/
        volumes:
            - ./:/var/www/html
        networks:
            - umkm
    db:
        image: mysql:5.7
        container_name: umkm-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./storage/mysql:/var/lib/mysql
        networks:
            - umkm
    nginx:
        image: nginx:1.17-alpine
        container_name: umkm-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www/html
            - ./:/etc/nginx/conf.d
        networks:
            - umkm
networks:
    umkm:
        driver: bridge